version: '3.8'

services:
  frontend:
    build:
      context: ./next-maikado-app
      dockerfile: Dockerfile
    container_name: maikado-frontend
    restart: unless-stopped
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: maikado-backend
    restart: unless-stopped
    env_file:
      - ./.env

  agents:
    build:
      context: ./agents
      dockerfile: Dockerfile
    container_name: maikado-agents
    restart: unless-stopped
    env_file:
      - ./.env
