import subprocess
import os
import json
import tempfile
import modal
from huggingface_hub import hf_hub_download # Necesario para la descarga de modelos

# --- 1. Configuración del Almacenamiento Persistente (Modal Volume) ---
# Usamos el Volumen para almacenar los modelos grandes de IA y evitar re-descargas.
vol = modal.Volume.from_name("hf-hub-cache", create_if_missing=True)

# --- 2. Definición de la Imagen del Contenedor (Modal Image) ---
# Se unifican todas las dependencias: ComfyUI, nodos personalizados, PyTorch, y Hugging Face.
comfyui_image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install("git") # Instalar git
    .pip_install("comfy-cli==1.4.1", force_build=True) # Instalar comfy-cli
    
    # Importante: Añadir PyTorch, vital para la ejecución de modelos de IA
    .pip_install("torch", "torchvision", "torchaudio") 
    
    # Instalar ComfyUI con dependencias NVIDIA
    .run_commands(
        "comfy --skip-prompt install --fast-deps --nvidia --version 0.3.47",
        force_build=True,
    )
    
    # Instalar nodos personalizados (Tomado de ambos códigos)
    .run_commands(
        "comfy node install --fast-deps was-node-suite-comfyui@1.0.2",
        "git clone https://github.com/ChenDarYen/ComfyUI-NAG.git /root/comfy/ComfyUI/custom_nodes/ComfyUI-NAG",
        "git clone https://github.com/kijai/ComfyUI-KJNodes.git /root/comfy/ComfyUI/custom_nodes/ComfyUI-KJNodes",
        "git clone https://github.com/cubiq/ComfyUI_essentials.git /root/comfy/ComfyUI/custom_nodes/ComfyUI_essentials",
        force_build=True,
    )
    
    # Configurar para descargas rápidas desde Hugging Face (Tomado de Código 2)
    .pip_install("huggingface_hub[hf_transfer]>=0.34.0,<1.0")
    .env({"HF_HUB_ENABLE_HF_TRANSFER": "1"})
)

# --- 3. Función de Descarga de Modelos (Tomado de Código 2) ---
def hf_download():
    """Descarga modelos de IA y crea enlaces simbólicos en el directorio de ComfyUI."""
    
    # Instalación de huggingface_hub se realiza en la imagen, aquí la importamos
    
    # Descargar y enlazar el modelo principal Wan 2.2
    wan_model = hf_hub_download(
        repo_id="Comfy-Org/Wan_2.2_ComfyUI_Repackaged",
        filename="split_files/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors",
        cache_dir="/cache",
    )
    subprocess.run(
        f"ln -s {wan_model} /root/comfy/ComfyUI/models/diffusion_models/wan2.2_ti2v_5B_fp16.safetensors",
        shell=True, check=True,
    )

    # Descargar y enlazar el VAE
    vae_model = hf_hub_download(
        repo_id="Comfy-Org/Wan_2.2_ComfyUI_Repackaged",
        filename="split_files/vae/wan2.2_vae.safetensors",
        cache_dir="/cache",
    )
    subprocess.run(
        f"ln -s {vae_model} /root/comfy/ComfyUI/models/vae/wan2.2_vae.safetensors",
        shell=True, check=True,
    )

    # Descargar y enlazar el Text Encoder
    text_encoder_model = hf_hub_download(
        repo_id="Comfy-Org/Wan_2.1_ComfyUI_repackaged",
        filename="split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors",
        cache_dir="/cache",
    )
    subprocess.run(
        f"ln -s {text_encoder_model} /root/comfy/ComfyUI/models/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors",
        shell=True, check=True,
    )


# Ejecutar la función de descarga de modelos al construir la imagen
comfyui_image = comfyui_image.run_function(
    hf_download,
    volumes={"/cache": vol}, # Montar el volumen para la caché de modelos
)

# --- 4. Definición de la Aplicación y Funciones ---
stub = modal.Stub("comfyui-combined-service") # Renombrado para la combinación

# --- 4A. Endpoint API para Integración (n8n) (Tomado de Código 1) ---
@stub.function(
    image=comfyui_image,
    gpu="L40S", # Usar GPU de alto rendimiento
    volumes={"/cache": vol}, # Montar el volumen para acceder a los modelos
    container_idle_timeout=300, # Apagar después de 5 minutos de inactividad
)
@modal.web_endpoint(method="POST")
def run_workflow(workflow: dict):
    """
    Recibe un workflow de ComfyUI (JSON) y lo ejecuta en modo batch.
    Ideal para integración con n8n.
    """
    
    # Guardar el workflow en un archivo temporal
    with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".json") as f:
        json.dump(workflow, f)
        workflow_path = f.name

    command = f"python /root/comfy/ComfyUI/main.py --load-api-workflow {workflow_path}"
    
    try:
        # Ejecutar el workflow
        subprocess.run(command, shell=True, check=True)
        
        # Buscar y devolver el archivo más reciente generado
        output_dir = "/root/comfy/ComfyUI/output"
        files = os.listdir(output_dir)
        
        if not files:
            return {"error": "No output file generated by the workflow."}
            
        latest_file = max(files, key=lambda f: os.path.getmtime(os.path.join(output_dir, f)))
        output_file_path = os.path.join(output_dir, latest_file)
        
        with open(output_file_path, "rb") as f:
            video_content = f.read()
            
        # Limpiar el output (opcional, pero buena práctica)
        for f in files:
            os.remove(os.path.join(output_dir, f))

        # El tipo de medio debe ser dinámico (e.g., video/mp4, image/png)
        # Por simplificación, se asume video/mp4 basado en el prompt original
        return modal.Response(video_content, media_type="video/mp4")

    except subprocess.CalledProcessError as e:
        return {"error": f"Error running ComfyUI workflow: {e.stderr.decode() if e.stderr else str(e)}"}
    except Exception as e:
        return {"error": f"An unexpected error occurred: {e}"}

# --- 4B. Servidor Web Interactivo (UI) para Acceso Regular (Tomado de Código 2) ---
@stub.function(
    image=comfyui_image,
    max_containers=1, # Limitar a una instancia interactiva
    gpu="L40S", 
    volumes={"/cache": vol}, # Montar el volumen para acceder a los modelos
)
@modal.concurrent(
    max_inputs=10 # Necesario para el proceso de inicio de la UI
)
@modal.web_server(8000, startup_timeout=60)
def ui():
    """
    Inicia el servidor web interactivo de ComfyUI.
    Ideal para que los usuarios accedan y diseñen workflows.
    """
    # Ejecutar el comando de lanzamiento de la UI de ComfyUI
    subprocess.Popen("python /root/comfy/ComfyUI/main.py --listen 0.0.0.0 --port 8000", shell=True)
